#!/usr/bin/env bash
# Configure domain zone so that the subdomain www points to the load-balancer (lb-01) IP.

if [ "$#" = 1 ]
then
	subdomain=("www" "110255-lb-01" "110255-web-02" "110255-web-02")
	for sub_domain in "${subdomains[@]}"
	do
		record_type=$(dig $sub_domain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
		destination=$(dig $sub_domain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
	echo "The subdomain $sub_domain is a $record_type record and points to $destination"
	done
elif [ "$#" = 2 ]
then
	record_type=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
	destination=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
	echo "The subdomain $2 is a $record_type record and points to $destination"
fi
