#!/bin/bash
# Configure domain zone to display information about subdomains
display_subdomain_info() {
    local record_type=$(dig $1.$2 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
    local destination=$(dig $1.$2 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
    echo "The subdomain $1 is a $record_type record and points to $destination"
}

if [ "$#" = 1 ]
then
    domain=$1
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${subdomains[@]}"
    do
        display_subdomain_info $sub_domain $domain
    done
elif [ "$#" = 2 ]
then
    display_subdomain_info $2 $1
fi
