#!/usr/bin/env bash
# Command to make an nginx server listen on port 80
link="/etc/nginx/sites-enabled/default"
target="/etc/nginx/sites-available/default"
sudo rm $link
sudo ln -s $target $link
sudo service nginx restart
