#!/usr/bin/env bash
# displays BEst school 10 times 4th bad luck 8 good luck

COUNTER=1
while [ $COUNTER -lt 11 ]
do
	if [ $COUNTER = 4 ]
	then
		echo "bad luck"
	elif [ $COUNTER = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( COUNTER+=1 ))
done
