#!/usr/bin/env bash
# Nginx is running as the nginx user.
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo chmod -R 700 /etc/nginx/nginx.conf
pkill apache2
sudo udo -u nginx service nginx restart
